// HIDE UNUSED FLEXFORM FIELDS
//============================================================
TCEFORM {
    tt_content {
        sys_language_uid.disabled = 1
        colPos.disabled = 0
        header_link.disabled = 0
        date.disabled = 1
        rowDescription.disabled = 1
        sectionIndex.disabled = 1
        linkToTop.disabled = 1

        tx_gridelements_container.disabled = 0
        tx_gridelements_columns.disabled = 0
    }
}

// HIDE UNUSED CONTENT TYPES
//============================================================
TCEFORM {
    tt_content {
        CType.removeItems = bullets
    }
}