styles:
  templates:
    layoutRootPath: 'EXT:cms_setup_kit/Resources/Private/ContentElements/Layouts/'
    partialRootPath: 'EXT:cms_setup_kit/Resources/Private/ContentElements/Partials/'
    templateRootPath: 'EXT:cms_setup_kit/Resources/Private/ContentElements/Templates/'
  content:
    textmedia:
      maxW: 1200
      maxWInText: 600
      linkWrap:
        lightboxEnabled: true
        lightboxCssClass: lightbox

page:
  pageview:
    paths: 'EXT:cms_setup_kit/Resources/Private/PageView/'

config:
  headerComment: ''
  pageTitleSeparator: ' - '
