mod {
    web_layout {
        BackendLayouts {
            blank-page {
                title = Blank page
                #icon = /Images/BackendLayouts/default_2_columns_25_75.gif
                config {
                    backend_layout {
                        colCount = 1
                        rowCount = 1

                        rows {
                            1 {
                                columns {
                                    1 {
                                        name = Content
                                        colPos = 0
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}