/*
*  EDYTUJ TEZ PLIK setup.tss
*/

#============================================================
# NAGLOWKI CONTENTU
#============================================================
TCEFORM.tt_content.header_layout {
    altLabels.0 = Default (H2)
    altLabels.1 = H2
    altLabels.2 = H1
    altLabels.3 = H3
    altLabels.4 = H4
    altLabels.5 = H5

    # DODATKOWE NAGLOWKI
    #========================================================
    addItems.6 = H2 z borderem dolnym


    # Hidden wyswietlany zawsze na koncu dropdowna
    #========================================================
    removeItems = 100
    addItems.99 = Hidden
}