// Remember to edit file ce_headers/setup.tss
// **********************************************************************

// CONTENT HEADERS
TCEFORM.tt_content.header_layout {
    altLabels.0 = Default (H2)
    altLabels.1 = H2
    altLabels.2 = H1
    altLabels.3 = H3
    altLabels.4 = H4
    altLabels.5 = H5

    // ADDITIONAL HEADERS
    addItems.6 = H2 with border

    // SET "HIDDEN" TO LAST POSITION ON LIST
    removeItems = 100
    addItems.99 = Hidden
}