mod {
    web_layout {
        BackendLayouts {
            subpage-one-col {
                title = Subpage wide
                #icon = /Images/BackendLayouts/default_2_columns_25_75.gif
                config {
                    backend_layout {
                        colCount = 1
                        rowCount = 1

                        rows {
                            1 {
                                columns {
                                    1 {
                                        name = Main container
                                        colPos = 0
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}