// DISABLE UNUSED FLEXFORM FIELDS
// **********************************************************************

TCEFORM {
    tt_content {
        CType.removeItems = bullets,multimedia

        sys_language_uid.disabled = 1
        header_position.disabled = 0
        colPos.disabled = 0
        spaceBefore.disabled = 1
        spaceAfter.disabled = 1
        header_position.disabled = 1
        header_link.disabled = 0
        date.disabled = 1
    }
}